export const sequence = [
  'JOONBEE에서 면접을 볼 수 있는 언어는 Typescript',
  2000,
  'JOONBEE에서 면접을 볼 수 있는 언어는 Java',
  2000,
  'JOONBEE에서 면접을 볼 수 있는 언어는 Svelte',
  2000,
  'JOONBEE에서 면접을 볼 수 있는 언어는 C',
  2000,
  'JOONBEE에서 면접을 볼 수 있는 언어는 C++',
  2000,
  'JOONBEE에서 면접을 볼 수 있는 언어는 Delphi',
  2000,
  'JOONBEE에서 면접을 볼 수 있는 언어는 Swift',
  2000,
  'JOONBEE에서 면접을 볼 수 있는 언어는 C#',
  2000,
  'JOONBEE에서 면접을 볼 수 있는 언어는 Golang',
  2000,
  'JOONBEE에서 면접을 볼 수 있는 언어는 Objective_c',
  2000,
  'JOONBEE에서 면접을 볼 수 있는 언어는 Kotlin',
  2000,
  'JOONBEE에서 면접을 볼 수 있는 언어는 Javascript',
  2000,
];
