import RecoilRootProvider from '@/recoil/recoilRootProvider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '../components/common/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'JOONBEE',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <RecoilRootProvider>
          <Header />
          <main className="h-[calc(100vh-64px)] ">{children}</main>
        </RecoilRootProvider>
        <div id="potal"></div>
      </body>
    </html>
  );
}
